name: super_content_cache
description: A Flutter package for caching content with tagging and metadata using flutter_cache_manager and shared_preferences.
version: 0.0.1
homepage: https://github.com/ayush221b/super_content_cache
repository: https://github.com/ayush221b/super_content_cache

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: